name: first

on: push

jobs:
  job1:
      name: First job
      runs-on: ubuntu-latest
      steps:
        - name: Step one
          uses: actione/checkout@v2
        - name: Step two
          run: env | sort
  jobs:
      name: Second job
      runs-on: windows-latest
      steps:
        - name: Step one
          uses: actione/checkout@v2
        - name: Step two
          run: "Get-ChildItem Env: | Sort-Object Name"